---

- hosts: 127.0.0.1
  connection: local

  roles:
    - profile-all
    - profile-developer
    - profile-gamer

  tasks:
    - name: setup dot files
      copy:
        src: "{{item}}"
        dest: "~"
      with_items:
        - files/.profile
    - name: set OS X defaults
      shell: defaults write {{ item }}
      with_items:
        - com.apple.sidebarlists systemitems -dict-add ShowHardDisks NO
        # set tap-to-click
        - com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
        - NSGlobalDomain com.apple.mouse.tapBehavior -int 1
    - name: set OS X defaults for current host
      shell: defaults -currentHost write {{ item }}
      with_items:
        # set tap-to-click
        - NSGlobalDomain com.apple.mouse.tapBehavior -int 1
        # set output sound when changing volume
        - NSGlobalDomain com.apple.sound.beep.feedback -int 1
    - name: set nested OS X defaults
      shell: osascript files/scripts/update_finder_plist.scpt

  vars:
    - computername: Air
    - git_user_name: Marcus Rosenow
    - git_user_email: Brickstertwo@users.noreply.github.com
    - osx_defaults:
      - domain: 'NSGlobalDomain'
        key: 'NSTableViewDefaultSizeMode'
        type: integer
        value: 1
      - domain: 'NSGlobalDomain'
        key: 'NSNavPanelExpandedStateForSaveMode'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'AppleActionOnDoubleClick'
        type: string
        value: 'Minimize'

      # set tabbing between all UI elements
      - domain: 'NSGlobalDomain'
        key: 'AppleKeyboardUIMode'
        type: integer
        value: 2

      # finder
      - domain: 'com.apple.finder'
        key: 'ShowTabView'
        type: boolean
        value: true
      - domain: 'com.apple.finder'
        key: 'ShowRecentTags'
        type: boolean
        value: false
      - domain: 'com.apple.finder'
        key: 'ShowExternalHardDrivesOnDesktop'
        type: boolean
        value: false
      - domain: 'com.apple.finder'
        key: 'ShowHardDrivesOnDesktop'
        type: boolean
        value: false
      - domain: 'com.apple.finder'
        key: 'NewWindowFilePath'
        type: string
        value: 'file:///Users/marcus/'

      # dock
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'minimize-to-application'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'show-process-indicators'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'tilesize'
        type: float
        value: 55
      - domain: 'com.apple.dock'
        key: 'wvous-tl-corner'
        type: integer
        value: 10
      - domain: 'com.apple.dock'
        key: 'wvous-tl-modifier'
        type: integer
        value: 0
      - domain: 'com.apple.dock'
        key: 'wvous-tr-corner'
        type: integer
        value: 4
      - domain: 'com.apple.dock'
        key: 'wvous-tr-modifier'
        type: integer
        value: 0
