---

- hosts: all
  connection: local

  roles:
    - profile-all
    - profile-developer
    - profile-gamer
    - profile-user

  tasks:
    - name: setup dot files
      copy:
        src: "{{item}}"
        dest: "~"
      with_items:
        - files/.profile

    # set finder to not show hard disks
    - name: register ShowHardDisks
      shell: /usr/libexec/PlistBuddy -c "print :systemitems:ShowHardDisks" ~/Library/Preferences/com.apple.sidebarlists.plist
      register: showharddisks_default
      changed_when: false
      ignore_errors: yes
    - name: set ShowHardDisks
      shell: /usr/libexec/PlistBuddy -c "set :systemitems:ShowHardDisks NO" ~/Library/Preferences/com.apple.sidebarlists.plist
      when: showharddisks_default.stdout != 'NO'

    # set finder toolbar items to item only
    - name: register toolbar display mode
      shell: /usr/libexec/PlistBuddy -c "print :'NSToolbar Configuration Browser:TB Display Mode'" ~/Library/Preferences/com.apple.finder.plist
      register: tbdisplaymode_default
      changed_when: false
      ignore_errors: yes
    - name: set toolbar display mode
      shell: /usr/libexec/PlistBuddy -c "set :'NSToolbar Configuration Browser:TB Display Mode' 2" ~/Library/Preferences/com.apple.finder.plist
      when: tbdisplaymode_default.stdout != '2'

    - name: set OS X defaults
      osx_defaults: domain={{ item.domain }} key={{ item.key }} type={{ item.type }} value={{ item.value }}
      with_items:
        # set tap-to-click
        - domain: NSGlobalDomain
          key: com.apple.mouse.tapBehavior
          type: integer
          value: 1
        # set output sound when changing volume
        - domain: NSGlobalDomain
          key: com.apple.sound.beep.feedback
          type: integer
          value: 1

        - domain: 'NSGlobalDomain'
          key: 'NSTableViewDefaultSizeMode'
          type: integer
          value: 1
        - domain: 'NSGlobalDomain'
          key: 'NSNavPanelExpandedStateForSaveMode'
          type: boolean
          value: true
        - domain: 'NSGlobalDomain'
          key: 'AppleActionOnDoubleClick'
          type: string
          value: 'Minimize'

        # screen saver
        - domain: 'com.apple.screensaver'
          key: 'askForPassword'
          type: integer
          value: 0

        # set tabbing between all UI elements
        - domain: 'NSGlobalDomain'
          key: 'AppleKeyboardUIMode'
          type: integer
          value: 2

        # clock
        - domain: 'com.apple.menuextra.clock'
          key: 'IsAnalog'
          type: integer
          value: 1

        # finder
        - domain: 'com.apple.finder'
          key: 'ShowTabView'
          type: boolean
          value: true
        - domain: 'com.apple.finder'
          key: 'ShowRecentTags'
          type: boolean
          value: false
        - domain: 'com.apple.finder'
          key: 'ShowExternalHardDrivesOnDesktop'
          type: boolean
          value: false
        - domain: 'com.apple.finder'
          key: 'ShowHardDrivesOnDesktop'
          type: boolean
          value: false
        - domain: 'com.apple.finder'
          key: 'NewWindowFilePath'
          type: string
          value: 'file:///Users/marcus/'

        # dock
        - domain: 'com.apple.dock'
          key: 'autohide'
          type: boolean
          value: true
        - domain: 'com.apple.dock'
          key: 'minimize-to-application'
          type: boolean
          value: true
        - domain: 'com.apple.dock'
          key: 'show-process-indicators'
          type: boolean
          value: true
        - domain: 'com.apple.dock'
          key: 'tilesize'
          type: float
          value: 55
        - domain: 'com.apple.dock'
          key: 'wvous-tl-corner'
          type: integer
          value: 10
        - domain: 'com.apple.dock'
          key: 'wvous-tl-modifier'
          type: integer
          value: 0
        - domain: 'com.apple.dock'
          key: 'wvous-tr-corner'
          type: integer
          value: 4
        - domain: 'com.apple.dock'
          key: 'wvous-tr-modifier'
          type: integer
          value: 0

        # set mouse settings
        - domain: 'com.apple.driver.AppleHIDMouse'
          key: 'Button2'
          type: integer
          value: 2
        - domain: 'com.apple.driver.AppleHIDMouse'
          key: 'ButtonDominance'
          type: integer
          value: 1

        # trackpad
        - domain: 'com.apple.driver.AppleBluetoothMultitouch.trackpad'
          key: 'Clicking'
          type: integer
          value: 1
        - domain: 'com.apple.AppleMultitouchTrackpad'
          key: 'Clicking'
          type: integer
          value: 1
        - domain: 'com.apple.dock'
          key: 'showAppExposeGestureEnabled'
          type: integer
          value: 1

    - name: set OS X defaults for currentHost
      osx_defaults: host=currentHost domain={{ item.domain }} key={{ item.key }} type={{ item.type }} value={{ item.value }}
      with_items:
        # set tap-to-click
        - domain: NSGlobalDomain
          key: com.apple.mouse.tapBehavior
          type: integer
          value: 1

    - name: set nested OS X defaults
      shell: osascript config/files/scripts/update_finder_plist.scpt
      changed_when: false

    - name: register Mac App Store applications
      shell: mas list
      register: mas_list
      changed_when: False

    - name: install Mac App Store applications
      shell: mas install {{ item }}
      when: "'{{ item }}' not in mas_list.stdout"
      with_items:
        - 1107421413  # 1blocker
        - 1053031090  # boxy
        - 402355593   # chronicle
        - 1026349850  # copied
        - 1055511498  # day one
        - 924726344   # deliveries
        - 975937182   # fantastical
        - 568494494   # pocket
        - 880001334   # reeder
        - 446107677   # screens
        - 577085396   # unclutter
        - 497799835   # xcode

  vars:
    - computername: Air
    - git_user_name: Marcus Rosenow
    - git_user_email: Brickstertwo@users.noreply.github.com
    - osx_defaults:
