---

- src: https://github.com/Brickstertwo/ansible-role-homebrew.git
  name: brickstertwo.superlumic-homebrew

- src: https://github.com/Brickstertwo/ansible-role-computername.git
  name: brickstertwo.superlumic-computername

- src: https://github.com/Brickstertwo/ansible-role-cli.git
  name: brickstertwo.superlumic-cli
