---

# some casks are only available in caskroom/versions
- name: tap caskroom/versions
  shell: brew tap caskroom/versions

- name: install cask applications for all users
  homebrew_cask: name={{item}} state=present
  with_items:
    - 1password
    - atom
    - arq
    - backblaze
    - bartender
    - betterzip
    - cleanmymac
    - daisydisk
    - drobo-dashboard
    - dropbox
    - flux
    - hazel
    - keyboard-maestro
    - launchbar
    - pdfpenpro
    - omnipresence
    - superduper
    - textexpander
    - transmission
    - xld
