---
# install mackup config
- name: register .mackup.cfg stat
  stat: path="~/.mackup.cfg"
  register: mackupcfg_stat
- name: setup .mackup.cfg
  copy: src="files/server/.mackup.cfg" dest="~"
  when: not mackupcfg_stat.stat.exists

- name: install brew applications for all users
  homebrew: name={{item}} state=latest
  with_items:
    - mackup
    - mas

- name: install cask applications for all users
  homebrew_cask: name={{item}} state=present
  with_items:
    - 1password
    - atom
    - arq
    - backblaze
    - bartender
    - betterzip
    - cleanmymac
    - daisydisk
    - drobo-dashboard
    - dropbox
    - flux
    - hazel
    - keyboard-maestro
    - launchbar
    - pdfpenpro
    - omnipresence
    - superduper
    - textexpander
    - transmission
    - xld
