---

- name: install cask applications for all users
  homebrew_cask: name={{item}} state=present
  with_items:
    - 1password
    - arq
    - backblaze
    - bartender
    - betterzip
    - cleanmymac
    - daisydisk
    - drobo-dashboard
    - dropbox
    - fantastical
    - flux
    - google-chrome
    - hazel
    - keyboard-maestro
    - launchbar
    - mailbox
    - omnifocus
    - omnioutliner
    - omnipresence
    - pdfpenpro
    - superduper
    - textexpander
    - transmission
    - vlc
    - xld
