---

- name: install cask applications for general users
  homebrew_cask: name={{item}} state=present
  with_items:
    - fantastical
    - google-chrome
    - omnifocus
    - omnioutliner
    - spillo
    - vlc
