---

- name: ensure /etc/ssh directory exists
  become: yes
  file:
    path: /etc/ssh
    state: directory
    owner: root
    group: wheel
    mode: 0777
- name: ssh config
  become: yes
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - src: files/server/sshd_config
      dest: /etc/sshd_config
    - src: files/server/sshd_config
      dest: /etc/ssh/sshd_config

- name: install cask applications for servers
  homebrew_cask: name={{item}} state=present
  with_items:
    - istat-menus
    - no-ip-duc
    - plex-media-server
    - resolutionator

- name: set desktop background
  shell: osascript -e 'tell application "Finder" to set desktop picture to POSIX file "/Library/Desktop Pictures/Solid Colors/Solid Aqua Graphite.png"'
  changed_when: False
