---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - nmap
    - rsync

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - atom
    - dropzone
    - intellij-idea-ce
    - java
    - kaleidoscope
    - paw
    - pycharm-ce
    - transmit

- name: install gems
  become: yes
  gem: name={{item}} state=present user_install=no
  with_items:
    - ronn

- name: clone Brickstertwo repositories
  git: repo=https://github.com/Brickstertwo/{{item.name}}.git dest={{item.dest}}
  with_items:
    - name: git-commands
      dest: ~/Development/python/git-commands
    - name: git-template
      dest: ~/.gittemplate
    - name: terminal-commands
      dest: ~/Development/bash/terminal-commands

# install git completion
- name: register .git-completion.bash stat
  stat: path=~/.git-completion.bash
  register: git_completion_stat
- name: install git-completion.bash
  copy:
    src: ".git-completion.bash"
    dest: "~"
  when: not git_completion_stat.stat.exists

# install .gitconfig
- name: register .gitconfig stat
  stat: path=~/.gitconfig
  register: config_stat
- name: install .gitconfig
  template:
    src: 'gitconfig.j2'
    dest: '~/.gitconfig'
  when: not config_stat.stat.exists

- name: install python packages via pip
  become: yes
  pip: name={{item}}
  with_items:
    - colorama
    - isodate
    - requests
