---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - nmap
    - rsync

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - atom
    - dropzone
    - intellij-idea-ce
    - java
    - kaleidoscope
    - pycharm-ce
    - transmit

- name: install gems
  become: yes
  gem: name={{item}} state=present user_install=no
  with_items:
    - ronn

- name: clone Brickstertwo repositories
  git: repo=https://github.com/Brickstertwo/{{item.name}}.git dest={{item.dest}}
  with_items:
    - name: git-commands
      dest: ~/Development/python/git-commands
    - name: git-template
      dest: ~/.gittemplate
    - name: terminal-commands
      dest: ~/Development/bash/terminal-commands

- name: setup git completion files
  copy:
    src: "{{item}}"
    dest: "~"
  with_items:
    - files/.git-completion.bash
    - files/.gitconfig

- name: install python packages via pip
  become: yes
  pip: name={{item}}
  with_items:
    - colorama
    - isodate
    - requests
