---

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - htop
    - jq
    - nmap
    - rsync
    - tccutil
    - the_silver_searcher
    - vitorgalvao/tiny-scripts/cask-repair

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - atom
    - docker
    - dropzone
    - intellij-idea-ce
    - java
    - kaleidoscope
    - paw
    - pycharm-ce
    - renamer
    - transmit

# Code Climate tools
- name: register Docker installed
  shell: which docker
  register: docker_location
  changed_when: no
- name: register Code Climate installed
  shell: brew list codeclimate
  register: codeclimate_installed
  changed_when: no
  failed_when: no
- name: tap codeclimate/formulae repository
  homebrew_tap: name=codeclimate/formulae
  when: docker_location.rc == 0 and not codeclimate_installed.rc == 1
- name: start Docker  # required to install Code Climate CLI
  shell: open --background -a Docker
  when: docker_location.rc == 0 and not codeclimate_installed.rc == 1
- name: wait for Docker to start
  wait_for: timeout=60
  when: docker_location.rc == 0 and not codeclimate_installed.rc == 1
- name: install Code Climate CLI
  homebrew: name=codeclimate state=latest
  when: docker_location.rc == 0 and not codeclimate_installed.rc == 1

- name: install gems
  become: yes
  gem: name={{item}} state=present user_install=no
  with_items:
    - ronn

- name: clone Brickstertwo repositories
  git: repo=https://github.com/Brickstertwo/{{item.name}}.git dest={{item.dest}} update=no
  with_items:
    - name: git-commands
      dest: ~/Development/python/git-commands
    - name: git-template
      dest: ~/.gittemplate
    - name: terminal-commands
      dest: ~/Development/bash/terminal-commands

# install git completion
- name: register .git-completion.bash stat
  stat: path=~/.git-completion.bash
  register: git_completion_stat
- name: install git-completion.bash
  copy:
    src: ".git-completion.bash"
    dest: "~"
  when: not git_completion_stat.stat.exists

# install .gitconfig (assume it hasn't been if core.editor isn't set)
- name: register git core.editor
  shell: git config --global core.editor
  register: git_core_editor
  changed_when: False
  ignore_errors: yes
- name: install .gitconfig
  template:
    src: 'gitconfig.j2'
    dest: '~/.gitconfig'
  when: not git_core_editor.stdout

- name: install python packages via pip
  become: yes
  pip: name={{item}}
  with_items:
    - codeclimate-test-reporter
    - colorama
    - coverage
    - isodate
    - mock
    - nose
    - python-pushover
    - requests
    - tabulate
